export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CALCULATE_SUBTOTAL = "CALCULATE_SUBTOTAL";
export const CALCULATE_TAX = "CALCULATE_TAX";
export const CALCULATE_TOTAL = "CALCULATE_TOTAL";
export const APPLY_DISCOUNT = "APPLY_DISCOUNT";
export const RECALCULATE_DISCOUNT = "RECALCULATE_DISCOUNT";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
